name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build BNEOSTAKER
      run: |
        mkdir bneostaker
        cd bneostaker
        dotnet new -i Neo3.SmartContract.Templates::1.5.0
        dotnet new neo3-contract
        dotnet build
        mv bin/sc/* ./
        rm -rf bin
        rm -rf obj
    - name: Release
      run: |
        git config --global user.email "neoburger@neoburger.github.io"
        git config --global user.name "neoburger"
        git checkout -b release
        git add .
        git commit -m 'release'
        git push -f origin release